---
- name: Set up repo
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{ item }}"
  with_items:
    - "deb http://{{ cl_apt_mirror }} CumulusLinux-3 cumulus upstream"
    - "deb http://{{ cl_apt_mirror }} CumulusLinux-3-security-updates cumulus upstream"
    - "deb http://{{ cl_apt_mirror }} CumulusLinux-3-updates cumulus upstream"
  tags:
    - repo

- name: Add mirrored debian jessie repository
  apt_repository:
    repo: deb http://{{ cl_apt_mirror }}/debian jessie main
    state: present
    filename: jessie
    update_cache: no
  when: debian_mirror == 'yes'
  tags:
    - repo
...
