---
- name: Remove cumulus repositories
  lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: 'repo3.cumulusnetworks.com'

- name: Add mirrored cumulus repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: cumulus
    update_cache: no
  with_items:
    - deb http://{{ cl_apt_mirror }} CumulusLinux-3 cumulus upstream
    - deb http://{{ cl_apt_mirror }} CumulusLinux-3-security-updates cumulus upstream
    - deb http://{{ cl_apt_mirror }} CumulusLinux-3-updates cumulus upstream

- name: Add mirrored debian jessie repository
  apt_repository:
    repo: deb http://{{ cl_apt_mirror }}/debian jessie main
    state: present
    filename: jessie
    update_cache: no
  when: debian_mirror == 'yes'
...
