---
# Set apt-mirror repo's on the oob mgmt server.
- name: Add apt-mirror repo on mgmt server for jessie main
  apt_repository:
    repo: deb http://{{ cl_oob_server }}/debian jessie main
    state: present
    filename: mgmt-jessie
  notify: Update apt cache

- name: Replace cumulus repo with mirrored one
  replace:
    dest: /etc/apt/sources.list
    regexp: 'repo3.cumulusnetworks.com'
    replace: '{{ cl_oob_server }}'
  notify: Update apt cache
...
