---
# Set apt-mirror repo's on the oob mgmt server.
- name: Replace cumulus repo with mirrored one
  replace:
    dest: /etc/apt/sources.list
    regexp: 'repo3.cumulusnetworks.com'
    replace: '{{ cl_apt_mirror }}'

- name: Add apt-mirror repo on mgmt server for jessie main
  apt_repository:
    repo: deb http://{{ cl_apt_mirror }}/debian jessie main
    state: present
    filename: mgmt-jessie
    update_cache: no
...
